[package]
name = "diffly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.3.1"
futures = "0.3.25"
tokio = "1.21.2"
serde = "1.0.147"